services:
  pdf-service:
    image: sbom-report-generator:latest
    depends_on:
      logo-service:
        condition: service_healthy

  logo-service:
    image: logo-service:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://logo-service:8000/info"]
      start_period: 20s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3