services:
  # pdf-service:
  #   image: sbom-report-generator:latest
  #   ports:
  #     - 8080:8080

  logo-service-cors:
    image: logo-service:latest
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 8081:80