services:
  pdf-service:
    image: sbom-report-generator:latest
    ports:
      - 8080:8080

  logo-service:
    image: logo-service-cors:latest
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 8081:80

  simple-proxy:
    build: ./proxydemo
    environment:
      LOGO_SERVICE_HOST: http://logo-service:8000
    ports:
      - 8082:8080