name: service-composition-auth

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-microservices.json:/opt/keycloak/data/import/realm.json
    command: ["start-dev", "--import-realm"]
    ports:
      - 8080:8080